#!/bin/sh

######################################################################
# dirsearch                                                          #
# Script by: Annwan                                                  #
######################################################################
# Description:                                                       #
# grep a pattern in a direcrory of files                             #
######################################################################
# Usage:                                                             #
# dirsearch <directory> <pattern>                                    #
######################################################################

DIR=$1
QUERY=$2
for FILE in $(/bin/ls -pL "$DIR"*)
do
    echo "$FILE"
    echo "$(/bin/grep "$QUERY" "$FILE")"
done
