#!/bin/sh

########################################################################
# escaper                                                              #
# script by: Annwan                                                    #
########################################################################
# Description                                                          #
# Little script to insert ANSI escape codes and special chars into an  #
# output                                                               #
########################################################################

while test "$1" != "" ; do
	case $1 in
		# 1 Byte hex
		@X1B)		printf "\x$2"; shift ;;
		# 3 oct-dig
		@OCT)		printf "\\$2"; shift ;;
		# 2 Byte hex
		@X2B)		printf "\u$2"; shift ;;
		# 4 Byte hex
		@X4B)		printf "\U$2"; shift ;;
		# Tab
		@TAB)		printf "\011" ;;
		# Space
		@SPC)		printf "\040" ;;
		# Escape
		@ESC)		printf "\e" ;;
		# New Line
		@LF)		printf "\n" ;;
		# Foreground
		@FGBK)		printf "\e[38;5;0m" ;;
		@FGRD)		printf "\e[38;5;1m" ;;
		@FGGR)		printf "\e[38;5;2m" ;;
		@FGYL)		printf "\e[38;5;3m" ;;
		@FGBU)		printf "\e[38;5;4m" ;;
		@FGVT|@FGPP)	printf "\e[38;5;5m" ;;
		@FGAQ)		printf "\e[38;5;6m" ;;
		@FGWH)		printf "\e[38;5;7m" ;;
		@FGBBK)		printf "\e[38;5;8m" ;;
		@FGBRD)		printf "\e[38;5;9m" ;;
		@FGBGR)		printf "\e[38;5;10m" ;;
		@FGBYL)		printf "\e[38;5;11m" ;;
		@FGBBU)		printf "\e[38;5;12m" ;;
		@FGBVT|@FGBPP)	printf "\e[38;5;13m" ;;
		@FGBAQ)		printf "\e[38;5;14m" ;;
		@FGBWH)		printf "\e[38;5;15m" ;;
		# Background
		@BGBK)		printf "\e[48;5;0m" ;;
		@BGRD)		printf "\e[48;5;1m" ;;
		@BGGR)		printf "\e[48;5;2m" ;;
		@BGYL)		printf "\e[48;5;3m" ;;
		@BGBU)		printf "\e[48;5;4m" ;;
		@BGVT|@BGPP)	printf "\e[48;5;5m" ;;
		@BGAQ)		printf "\e[48;5;6m" ;;
		@BGWH)		printf "\e[48;5;7m" ;;
		@BGBBK)		printf "\e[48;5;8m" ;;
		@BGBRD)		printf "\e[48;5;9m" ;;
		@BGBGR)		printf "\e[48;5;10m" ;;
		@BGBYL)		printf "\e[48;5;11m" ;;
		@BGBBU)		printf "\e[48;5;12m" ;;
		@BGBVT|@BGBPP)	printf "\e[48;5;13m" ;;
		@BGBAQ)		printf "\e[48;5;14m" ;;
		@BGBWH)		printf "\e[48;5;15m" ;;
		# Font
		@BD)		printf "\e[1m" ;;
		@NOBD)		printf "\e[22m" ;;
		@UL)		printf "\e[4m" ;;
		@NOUL)		printf "\e[24m" ;;
		# Reset
		@RESET)		printf "\e[0m" ;;
		*)		printf "$1" ;;
	esac;
	shift;
done;
