#!/bin/bash

#######################################################################
# flasher                                                             #
# script by: Annwan                                                   #
#######################################################################
# Descriprion:                                                        #
# Flashes the screen until the user presses a key                     #
#######################################################################

while true; do
	printf '\x1b[?5h';
	sleep 0.1;
	printf '\x1b[?5l';
	read -n 1 -t 1 && break;
done;
