#!/bin/sh

######################################################################
# prettyman                                                          #
# Script by: Annwan                                                  #
######################################################################
# Dependencies:                                                      #
#  - zathura                                                         #
######################################################################
# Description:                                                       #
# prettyman is a simple wrapper script for man to display manpages   #
# as pdf, to make them more readable, and to allow to print them.    #
######################################################################


if [ -z $1 ]; then
	echo "Please specify the manual page you wish to see";
else
	TEMP_FILE=$(mktemp);
	man -Tps $@ | ps2pdf - $TEMP_FILE;
	zathura $TEMP_FILE;
	rm -r -f $TEMP_FILE;
fi

