#!/bin/sh

######################################################################
# rsslookup                                                          #
# Script by: Annwan                                                  #
######################################################################
# Dependencies:                                                      #
#  - rsstail                                                         #
######################################################################
# Description:                                                       #
# rsslookup is the script I use to manage my different rss feeds and #
# youtube non-subscriptions (letting me not having to use a Google   #
# account). Just add yours below                                     #
######################################################################

ytfeedc="https://www.youtube.com/feeds/videos.xml?channel_id="
ytfeedu="https://www.youtube.com/feeds/videos.xml?user="

args=" -pa -n 1 -i 3" #show date and author, start with only one item, refresh every 30 s

# Add your feeds below:
# Examples :
# args="$args -u example.com/rss.xml"
# args="$args -u ${ytfeedu}YTUserName"
# args="$args -u ${ytfeedc}YTChannelID"

clear

sh -c "(sleep 10; kill \"\$\$\") & exec rsstail $args" | less

